function [x0, y0, r] = mincircle_sqp(P)
	%  - Damien Loterie (03/2014)

    % Input check
    if size(P,2)~=2
       error('Wrong input dimensions'); 
    end
    
    % Starting guess
    x0 = mean(P,1);
    d2 = sum((P - repmat(x0,[size(P,1) 1])).^2, 2);
    x0 = [x0, sqrt(max(d2))];

%     % Reorder
%     [~, ind] = sort(d2);
%     P = P(ind,:);

    % Algorithm
    options = optimoptions(@fmincon,...
                           'Algorithm','sqp',...
                           'GradObj','on',...
                           'GradConstr','on',...
                           'Disp','off');%,...
                           %'PlotFcns',@(x,a,b)mincircle_plot(x(1),x(2),x(3),P));

    problem = struct('objective',@(x)mincircle_of(x(1),x(2),x(3)),...
                     'nonlcon',@(x)mincircle_nlc(x(1),x(2),x(3),P),...
                     'solver','fmincon',...
                     'x0',x0,...
                     'options',options,...
                     'Aineq',[],...
                     'bineq',[],...
                     'Aeq',[],...
                     'beq',[],...
                     'lb',[],...
                     'ub',[]);


    xmin = fmincon(problem);

    % Extract answer
    x0 = xmin(1);
    y0 = xmin(2);
    r = xmin(3);
end
