% Script defining test patterns to verify the TM measurement
%  - Damien Loterie (08/2015)

fiber_mask = holo_params.fiber.mask2;

% patterns = {pattern_spot(fiber_mask,0,0),...
%             pattern_line(fiber_mask,0,0,400),...
%             pattern_img(fiber_mask,'./img/a.png',0.75),...
%             pattern_img(fiber_mask,'./img/epfl.png',0.75),...
%             pattern_grating(fiber_mask,[0 0],[0 0]),...
%             pattern_grating(fiber_mask,[0 0],[15 -15]),...
%             pattern_grating(fiber_mask,[0 0],[30 -30]) ...
%             };


%      pattern_line(fiber_mask,0,0,400),... 


patterns = {pattern_spot(fiber_mask,0,0),...
            pattern_spot(fiber_mask,1,10),...
            };