reset_all;

% Fullscreen startup parameters
[x_slm, y_slm] = slm_size();

% Retreive the slm image obtained from Holoeye software for testing.
calibration_frame = imread('../holoeye_grating.jpg');
calibration_frame = calibration_frame(:,:,1);

% Open fullscreen window
addpath(dx_fullscreen_path);
dx_options = struct('monitor',      1,...
                    'screenWidth',  x_slm,...
                    'screenHeight', y_slm,...
                    'frameWidth',   x_slm,...
                    'frameHeight',  y_slm,...
                    'renderWidth',  x_slm,...
                    'renderHeight', y_slm,...
                    'renderPosX',   0,...
                    'renderPosY',   0);
d = dx_fullscreen(dx_options);

% d = dx_fullscreen;
vsync_config(d,10000);
% d.show(zeros(800,600,'uint8'));
% Show the calibration frame
d.show(calibration_frame(:,:,1)');



vid = camera_mex('distal','ElectronicTrigger');
exposure = 1000;
sequence_function = @(n)zeros(d.getConfig('frameWidth'),d.getConfig('frameHeight'),numel(n),'uint8');
number_of_frames = 100;
divider = 3;

metadata = measure_sequence(d, ...
                           vid, ...
                           exposure, ...
                           sequence_function, ...
                           number_of_frames,...
                           divider);